# Generated by Django 4.0.5 on 2022-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='age',
        ),
        migrations.RemoveField(
            model_name='test',
            name='grade',
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
