# Generated by Django 4.0.5 on 2022-06-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_test_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('calories', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
