# Generated by Django 4.0.5 on 2022-06-29 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_foodentry_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='assigned_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FoodEntry_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
