# Generated by Django 4.0.5 on 2022-06-29 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foodentry_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='assigned_to',
            new_name='user_id',
        ),
    ]
