# Generated by Django 4.0.5 on 2022-06-30 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rename_assigned_to_foodentry_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodentry',
            name='user_id',
        ),
        migrations.AddField(
            model_name='foodentry',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='FoodEntry_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
