# Generated by Django 4.0.5 on 2022-06-30 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_foodentry_user_id_foodentry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodentry',
            old_name='user',
            new_name='user_id',
        ),
    ]
