name: Zappa Django deployement
on:
  push:
    branches:
      - master
jobs:
  deploy-django-serverless:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setting up AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Create virtual env
        run: |
          pip install virtualenv
          python -m virtualenv env
      - name: Install Requirements
        run: |
          . env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          deactivate
      - name: Update Django application using zappa
        run: |
          . env/bin/activate
          zappa update dev
